ARDUINO_DIR = /opt/arduino-1.0

BOARD_TAG    = mega2560
ARDUINO_PORT = /dev/ttyUSB0

ARDUINO_LIBS = MemoryFree

AVR_TOOLS_PATH   = /usr/bin
AVRDUDE_CONF     = /etc/avrdude.conf

include ../Arduino.mk

